# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#060400"

# Main text color
theme[main_fg]="#cde1aa"

# Title color for boxes
theme[title]="#cde1aa"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#9ac400"

# Background color of selected item in processes box
theme[selected_bg]="#212d00"

# Foreground color of selected item in processes box
theme[selected_fg]="#9ac400"

# Color of inactive/disabled text
theme[inactive_fg]="#5d5b55"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#e4f2cc"

# Background color of the percentage meters
theme[meter_bg]="#212d00"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#e4f2cc"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#5a6ebc"
theme[mem_box]="#98c50c"
theme[net_box]="#98c419"
theme[proc_box]="#9ac400"

# Box divider line and small boxes line color
theme[div_line]="#5d5b55"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#98c50c"
theme[temp_mid]="#99c423"
theme[temp_end]="#98c419"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#596ebe"
theme[cpu_mid]="#586ec0"
theme[cpu_end]="#5a6ebc"

# Mem/Disk free meter
theme[free_start]="#5a6ebc"
theme[free_mid]="#586ec0"
theme[free_end]="#596ebe"

# Mem/Disk cached meter
theme[cached_start]="#586ec0"
theme[cached_mid]="#596ebe"
theme[cached_end]="#5a6ebc"

# Mem/Disk available meter
theme[available_start]="#99c423"
theme[available_mid]="#98c419"
theme[available_end]="#98c419"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#98c50c"
theme[used_mid]="#596ebe"
theme[used_end]="#586ec0"

# Download graph colors
theme[download_start]="#99c423"
theme[download_mid]="#98c419"
theme[download_end]="#98c419"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#98c50c"
theme[upload_mid]="#596ebe"
theme[upload_end]="#586ec0"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#596ebe"
theme[process_mid]="#586ec0"
theme[process_end]="#5a6ebc"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#060400"
theme[gradient_color_1]="#181202"
theme[gradient_color_2]="#212d00"
theme[gradient_color_3]="#5d5b55"
theme[gradient_color_4]="#728157"
theme[gradient_color_5]="#cde1aa"
theme[gradient_color_6]="#e4f2cc"
theme[gradient_color_7]="#f3fde4"
