background = #060400
foreground = #cde1aa
cursor-color = #f3fde4
selection-background = #212d00
selection-foreground = #f3fde4

palette = 0=#060400
palette = 1=#98c419
palette = 2=#98c50c
palette = 3=#99c423
palette = 4=#586ec0
palette = 5=#5a6ebc
palette = 6=#596ebe
palette = 7=#cde1aa
palette = 8=#5d5b55
palette = 9=#aee018
palette = 10=#afe024
palette = 11=#ade003
palette = 12=#6d88e8
palette = 13=#6f88e4
palette = 14=#6e88e6
palette = 15=#f3fde4
