foreground #cde1aa
background #060400
selection_foreground #f3fde4
selection_background #212d00

cursor #f3fde4
cursor_text_color #060400

active_border_color #9ac400
active_tab_background #9ac400

color0 #060400
color1 #98c419
color2 #98c50c
color3 #99c423
color4 #586ec0
color5 #5a6ebc
color6 #596ebe
color7 #cde1aa
color8 #5d5b55
color9 #aee018
color10 #afe024
color11 #ade003
color12 #6d88e8
color13 #6f88e4
color14 #6e88e6
color15 #f3fde4
